[package]
name = "golden_rust"
version = "0.0.0"
authors = ["nokx <info@nokx.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
